spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/batchwos
    username: root
    password:

  jpa:
    properties:
      hibernate:
#        show_sql: true
        hbm2dd:
          # 원래 이걸 쓰면 잘 됐었는데
          # 왜 테이블이 자동생성되지 않는가.
          # 이게 안먹고
          auto: update
        dialect: org.hibernate.dialect.MariaDBDialect
        enable_lazy_load_no_trans: true
    # 이게 먹는 이유를 찾아야함.
    # 버전 차이 때문에 생긴 차인가?
    # 애초에 jpa. 바로 아래 hibernate 형식으로 쓰는 건 처음보네
    hibernate:
      ddl-auto: create-drop

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/batchwos?characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password:
#
#  jpa:
#    properties:
#      hibernate:
#        hbm2dd:
#          auto: create
#        dialect: org.hibernate.dialect.MySQL5Dialect
#        enable_lazy_load_no_trans: true
#    show-sql: true